# Generated by Django 6.0.6 on 2026-06-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Каждый ингридиент с новой строки')),
                ('time_minutes', models.PositiveIntegerField(default=30)),
                ('difficulty', models.CharField(choices=[('easy', 'легко'), ('medium', 'средне'), ('hard', 'сложно')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='recipes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
